### ISSUE TITLE
Experiment 1 Out-of-Memory Error (Running with the SBT Command)

### ISSUE THREAD

**Issue by superctj** [dtim-upc/NextiaJD#2]
Hey Javier, thank you for releasing this detailed-documented repo! Really appreciate it.

I was trying to run Experiment 1 following the sbt command but I keep running into the out-of-memory error (java.lang.OutOfMemoryError: Java heap space) even I increase the heap size with the -Xmx flag or set spark.driver.memory to a larger number in the [NextiaJD_evaluation.scala](https://github.com/dtim-upc/NextiaJD/blob/96d955c347f6e01dd22f5a36e2543b3c2397b2fc/experiments/NextiaJD/src/main/scala/NextiaJD_evaluation.scala#L38) file. I suspect the configuration change is not in effect. Do u have any idea how to properly change configurations or fix the issue in general?

Here is the trace stack for your reference:
> [info] welcome to sbt 1.4.0 (Private Build Java 1.8.0_312)
> [info] loading settings for project nextiajd-build from plugins.sbt ...
> [info] loading project definition from /home/ubuntu/NextiaJD/experiments/NextiaJD/project
> [info] loading settings for project nextiajd from build.sbt ...
> [info] set current project to NextiaJD_experiment1 (in build file:/home/ubuntu/NextiaJD/experiments/NextiaJD/)
> [info] running NextiaJD_evaluation -d /data/nextiaJD_datasets/testbedXS/datasetInformation_testbedXS.csv -p /data/nextiaJD_datasets/testbedXS/datasets -g /data/nextiaJD_datasets/testbedXS/groundTruth_testbedXS.csv -o /data/nextiaJD_results/testbedXS/
> Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
> 22/06/13 20:13:46 INFO SparkContext: Running Spark version 3.1.0
> 22/06/13 20:13:46 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
> 22/06/13 20:13:46 INFO ResourceUtils: ==============================================================
> 22/06/13 20:13:46 INFO ResourceUtils: No custom resources configured for spark.driver.
> 22/06/13 20:13:46 INFO ResourceUtils: ==============================================================
> 22/06/13 20:13:46 INFO SparkContext: Submitted application: c0e2f7db-1098-4941-b66b-f5ef9638c378
> 22/06/13 20:13:46 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
> 22/06/13 20:13:46 INFO ResourceProfile: Limiting resource is cpu
> 22/06/13 20:13:46 INFO ResourceProfileManager: Added ResourceProfile id: 0
> 22/06/13 20:13:46 INFO SecurityManager: Changing view acls to: ubuntu
> 22/06/13 20:13:46 INFO SecurityManager: Changing modify acls to: ubuntu
> 22/06/13 20:13:46 INFO SecurityManager: Changing view acls groups to: 
> 22/06/13 20:13:46 INFO SecurityManager: Changing modify acls groups to: 
> 22/06/13 20:13:46 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(ubuntu); groups with view permissions: Set(); users  with modify permissions: Set(ubuntu); groups with modify permissions: Set()
> 22/06/13 20:13:47 INFO Utils: Successfully started service 'sparkDriver' on port 34691.
> 22/06/13 20:13:47 INFO SparkEnv: Registering MapOutputTracker
> 22/06/13 20:13:47 INFO SparkEnv: Registering BlockManagerMaster
> 22/06/13 20:13:47 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
> 22/06/13 20:13:47 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
> 22/06/13 20:13:47 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
> 22/06/13 20:13:47 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-a0287d81-188c-48c0-a955-b4d17f84fb6e
> 22/06/13 20:13:47 INFO MemoryStore: MemoryStore started with capacity 381.6 MiB
> 22/06/13 20:13:47 INFO SparkEnv: Registering OutputCommitCoordinator
> 22/06/13 20:13:47 INFO Utils: Successfully started service 'SparkUI' on port 4040.
> 22/06/13 20:13:47 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://ip-172-31-73-210.ec2.internal:4040
> 22/06/13 20:13:47 INFO Executor: Starting executor ID driver on host ip-172-31-73-210.ec2.internal
> 22/06/13 20:13:47 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40245.
> 22/06/13 20:13:47 INFO NettyBlockTransferService: Server created on ip-172-31-73-210.ec2.internal:40245
> 22/06/13 20:13:47 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
> 22/06/13 20:13:47 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, ip-172-31-73-210.ec2.internal, 40245, None)
> 22/06/13 20:13:47 INFO BlockManagerMasterEndpoint: Registering block manager ip-172-31-73-210.ec2.internal:40245 with 381.6 MiB RAM, BlockManagerId(driver, ip-172-31-73-210.ec2.internal, 40245, None)
> 22/06/13 20:13:47 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, ip-172-31-73-210.ec2.internal, 40245, None)
> 22/06/13 20:13:47 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, ip-172-31-73-210.ec2.internal, 40245, None)
> Testbed  has 28 datasets
> start profiling
> ...
> Discovery for property-tie-lines.csv
> [warn] 5.146 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
> [warn] 9.82 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
> [warn] 10.03 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
> [warn] 37.802 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
> [warn] 268.549 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
> [warn] 6.521 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
> [warn] 79.851 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
> [warn] 338.454 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
> [warn] 646.761 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
> [warn] 798.977 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
> 22/06/13 20:33:08 ERROR Executor: Exception in task 2.0 in stage 280.0 (TID 982)
> java.lang.OutOfMemoryError: Java heap space
>         at java.io.ObjectInputStream$HandleTable.grow(ObjectInputStream.java:3961)
>         at java.io.ObjectInputStream$HandleTable.assign(ObjectInputStream.java:3768)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2178)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
>         at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
>         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
>         at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
>         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
>         at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
>         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
>         at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
>         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
>         at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
>         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
>         at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
>         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
>         at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
>         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
> 22/06/13 20:33:08 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker for task 2.0 in stage 280.0 (TID 982),5,run-main-group-0]
> java.lang.OutOfMemoryError: Java heap space
>         at java.io.ObjectInputStream$HandleTable.grow(ObjectInputStream.java:3961)
>         at java.io.ObjectInputStream$HandleTable.assign(ObjectInputStream.java:3768)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2178)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
>         at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
>         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
>         at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
>         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
>         at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
>         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
>         at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
>         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
>         at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
>         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
>         at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
>         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
>         at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
>         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
>         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
> 22/06/13 20:33:09 ERROR TaskSetManager: Task 2 in stage 280.0 failed 1 times; aborting job
> 22/06/13 20:33:09 ERROR Utils: uncaught error in thread spark-listener-group-appStatus, stopping SparkContext
> java.lang.InterruptedException
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
>         at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
>         at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:110)
>         at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
>         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
>         at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
>         at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
>         at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381)
>         at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
> 22/06/13 20:33:09 ERROR FileFormatWriter: Aborting job 1cfbbca5-2431-47ef-a594-e1ec09c8ee9d.
> java.lang.InterruptedException
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
>         at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:242)
>         at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:258)
>         at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:187)
>         at org.apache.spark.util.ThreadUtils$.awaitReady(ThreadUtils.scala:334)
>         at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:859)
>         at org.apache.spark.SparkContext.runJob(SparkContext.scala:2202)
>         at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:200)
>         at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:188)
>         at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:108)
>         at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:106)
>         at org.apache.spark.sql.execution.command.DataWritingCommandExec.doExecute(commands.scala:131)
>         at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
>         at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
>         at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
>         at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
>         at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
>         at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
>         at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
>         at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
>         at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
>         at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
>         at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
>         at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
>         at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
>         at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
>         at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
>         at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
>         at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:293)
>         at org.apache.spark.sql.DataFrameWriter.csv(DataFrameWriter.scala:979)
>         at NextiaJD_evaluation$.$anonfun$run$5(NextiaJD_evaluation.scala:115)
>         at NextiaJD_evaluation$.$anonfun$run$5$adapted(NextiaJD_evaluation.scala:104)
>         at scala.collection.Iterator.foreach(Iterator.scala:943)
>         at scala.collection.Iterator.foreach$(Iterator.scala:943)
>         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
>         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
>         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
>         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
>         at NextiaJD_evaluation$.run(NextiaJD_evaluation.scala:104)
>         at NextiaJD_evaluation$.main(NextiaJD_evaluation.scala:251)
>         at NextiaJD_evaluation.main(NextiaJD_evaluation.scala)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at sbt.Run.invokeMain(Run.scala:133)
>         at sbt.Run.execute$1(Run.scala:82)
>         at sbt.Run.$anonfun$runWithLoader$5(Run.scala:110)
>         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
>         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:17)
>         at sbt.TrapExit$App.run(TrapExit.scala:258)
>         at java.lang.Thread.run(Thread.java:748)
> 22/06/13 20:33:09 ERROR Utils: throw uncaught fatal error in thread spark-listener-group-appStatus
> java.lang.InterruptedException
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
>         at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
>         at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:110)
>         at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
>         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
>         at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
>         at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
>         at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381)
>         at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
> 22/06/13 20:33:09 ERROR Utils: uncaught error in thread spark-listener-group-executorManagement, stopping SparkContext
> java.lang.InterruptedException
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
>         at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
>         at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:110)
>         at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
>         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
>         at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
>         at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
>         at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381)
>         at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
> 22/06/13 20:33:09 ERROR Utils: throw uncaught fatal error in thread spark-listener-group-executorManagement
> java.lang.InterruptedException
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
>         at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
>         at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:110)
>         at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
>         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
>         at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
>         at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
>         at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381)
>         at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
> 22/06/13 20:33:09 ERROR ContextCleaner: Error in cleaning thread
> java.lang.InterruptedException
>         at java.lang.Object.wait(Native Method)
>         at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
>         at org.apache.spark.ContextCleaner.$anonfun$keepCleaning$1(ContextCleaner.scala:182)
>         at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381)
>         at org.apache.spark.ContextCleaner.org$apache$spark$ContextCleaner$$keepCleaning(ContextCleaner.scala:180)
>         at org.apache.spark.ContextCleaner$$anon$1.run(ContextCleaner.scala:77)
> 22/06/13 20:33:09 ERROR Utils: uncaught error in thread spark-listener-group-shared, stopping SparkContext
> java.lang.InterruptedException
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
>         at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
>         at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:110)
>         at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
>         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
>         at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
>         at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
>         at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381)
>         at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
> 22/06/13 20:33:09 ERROR Utils: throw uncaught fatal error in thread spark-listener-group-shared
> java.lang.InterruptedException
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
>         at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
>         at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:110)
>         at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
>         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
>         at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
>         at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
>         at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381)
>         at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
> 22/06/13 20:33:09 ERROR Utils: Uncaught exception in thread executor-heartbeater
> java.lang.InterruptedException
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1039)
>         at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
>         at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:248)
>         at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:258)
>         at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
>         at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:293)
>         at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
>         at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:103)
>         at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:87)
>         at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:78)
>         at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:580)
>         at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1000)
>         at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:212)
>         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
>         at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1994)
>         at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> 22/06/13 20:33:09 ERROR SparkUncaughtExceptionHandler: Another uncaught exception in thread Thread[Executor task launch worker for task 2.0 in stage 280.0 (TID 982),5,run-main-group-0], process halted.

**Comment by Haross** [comment]
Hi Tianji, thanks for the interest. I'm still checking the problem, from what I see it's a problem with the java memory.  Could you replace the flag `-Xmx` with `-J-Xmx` as explained [here](https://www.scala-sbt.org/1.x/docs/Troubleshoot-Memory-Issues.html). Note, you have to indicate the memory assigned e.g., `-J-Xmx2G` (2 GB of memory) . The complete command would be like this:

```
sbt -J-Xmx2G "runMain NextiaJD_evaluation NextiaJD_evaluation -d /data/nextiaJD_datasets/testbedXS/datasetInformation_testbedXS.csv -p /data/nextiaJD_datasets/testbedXS/datasets -g /data/nextiaJD_datasets/testbedXS/groundTruth_testbedXS.csv -o /data/nextiaJD_results/testbedXS/"
```

Please let me know if it works for you?
Javier.

**Comment by superctj** [comment]
Thank you Javier! This works while 2GB was not enough and I used 5GB instead. Although it still gives me warnings like X out of last 10 seconds are used for garbage collection, the program runs to complete without errors.

**Comment by Haross** [comment]
I'm glad it works. I found the thing with the warning strange but could not replicate it. One thing to note is that ideally, NextiaJD will run better in a cluster environment so Apache Spark can take advantage of the parallelism.

Let us know if you have any feedback or encounter any issues.
We'd love to keep in touch ;-)

Best,
Javier
